packages:
  - shared
  - server
  - web

onlyBuiltDependencies:
  - esbuild
allowBuilds:
  '@mongodb-js/zstd': true
  core-js-pure: true
  esbuild: true
  node-liblzma: true
  sharp: true
  workerd: true
